// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	x "github.com/ad3n/x"
	mock "github.com/stretchr/testify/mock"
)

// ORMRepositoryInterface is an autogenerated mock type for the ORMRepositoryInterface type
type ORMRepositoryInterface struct {
	mock.Mock
}

// GetModel provides a mock function with given fields:
func (_m *ORMRepositoryInterface) GetModel() x.ModelInterface {
	ret := _m.Called()

	var r0 x.ModelInterface
	if rf, ok := ret.Get(0).(func() x.ModelInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(x.ModelInterface)
		}
	}

	return r0
}
